### ISSUE TITLE
Details of hardware 

### ISSUE THREAD

**Issue by ishwariyjoshi** [vpreatoni/triacdrv#1]
Sorry this is not an issues but. Can you provide schematic of this device.

**Comment by vpreatoni** [comment]
Hello Ishwariy Josh,

hardware is very simple, just Optotriac 3053 + Power Triac T835H connected
according to datasheet.

If you are interested, I sell assembled boards on Tindie or eBay to fund my
project:

https://www.tindie.com/products/vpreatoni/quad-opto-triac-hat/

https://www.ebay.com/itm/113873656775


Regards,
Victor
